### ISSUE TITLE
出去折腾了一圈又回来了，还是不行unknown option '--mode'

### ISSUE THREAD

**Issue by fxqy** [lc-ui/lcui-router-app#2]
又去duilib那折腾了一圈，还是需要装vcpkg，他那个更麻烦，又回来了，还是觉得lcui优雅。这次vs2015，vcpkg，lcpkg都装成功了，但是按照github readme上的还是不行，命令参数不对，希望帮我解决下。
```
PS D:\lcui-router-app> npm install
up to date in 1.501s

1 package is looking for funding
  run `npm fund` for details

PS D:\lcui-router-app> npm fund
lcui-router-app@0.1.0
`-- https://github.com/sponsors/sindresorhus
  `-- is-finite@1.1.0

PS D:\lcui-router-app> lcpkg run start --mode debug
error: unknown option '--mode'
PS D:\lcui-router-app> cd ..\lcui-quick-start\
PS D:\lcui-quick-start> lcpkg run start --mode debug
error: unknown option '--mode'
PS D:\lcui-quick-start>
```
![image](https://user-images.githubusercontent.com/42601163/102704031-83a1dd80-42b1-11eb-94a2-08eeab5ecba2.png)

**Comment by fxqy** [comment]
powershell找不到的问题虽然通过ln -s软连接的方式解决了，但还是不行
```
PATH=$PATH:'/c/Program Files/powershell
ln -s '/c/Program Files/powershell/pwsh.exe' '/c/Program Files/powershell/powershell.exe'
```
报错信息：
```
# lcpkg setup
vcpkg root directory was not found
warning: 不建议在没有为偏离分支指定合并策略时执行 pull 操作。 您可以在执行下一次
pull 操作之前执行下面一条命令来抑制本消息：

  git config pull.rebase false  # 合并（缺省策略）
  git config pull.rebase true   # 变基
  git config pull.ff only       # 仅快进

您可以将 "git config" 替换为 "git config --global" 以便为所有仓库设置
缺省的配置项。您也可以在每次执行 pull 命令时添加 --rebase、--no-rebase，
或者 --ff-only 参数覆盖缺省设置。

已经是最新的。
The argument '& {& 'C:\Users\Dong\.lcpkg\repos\vcpkg\scripts\bootstrap.ps1' }' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Usage: pwsh[.exe] [-Login] [[-File] <filePath> [args]]
                  [-Command { - | <script-block> [-args <arg-array>]
                                | <string> [<CommandParameters>] } ]
                  [-ConfigurationName <string>] [-CustomPipeName <string>]
                  [-EncodedCommand <Base64EncodedCommand>]
                  [-ExecutionPolicy <ExecutionPolicy>] [-InputFormat {Text | XML}]
                  [-Interactive] [-MTA] [-NoExit] [-NoLogo] [-NonInteractive] [-NoProfile]
                  [-OutputFormat {Text | XML}] [-SettingsFile <filePath>] [-STA] [-Version]
                  [-WindowStyle <style>] [-WorkingDirectory <directoryPath>]

       pwsh[.exe] -h | -Help | -? | /?

PowerShell Online Help https://aka.ms/powershell-docs

All parameters are case-insensitive.
child_process.js:669
    throw err;
    ^

Error: Command failed: .\bootstrap-vcpkg.bat
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Command.setup (D:\nodejs\nodeGlobal\node_modules\lcpkg\src\cli-setup.js:22:3)
    at Command.listener [as _actionHandler] (D:\nodejs\nodeGlobal\node_modules\lcpkg\node_modules\commander\index.js:426:31)
    at Command._parseCommand (D:\nodejs\nodeGlobal\node_modules\lcpkg\node_modules\commander\index.js:1002:14)
    at Command.parse (D:\nodejs\nodeGlobal\node_modules\lcpkg\node_modules\commander\index.js:801:10)
    at Object.<anonymous> (D:\nodejs\nodeGlobal\node_modules\lcpkg\src\cli-setup.js:28:4)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32) {
  status: 64,
  signal: null,
  output: [ null, null, null ],
  pid: 2492,
  stdout: null,
  stderr: null
}
```
![2020-12-16_213830](https://user-images.githubusercontent.com/42601163/102355618-13603700-3fe7-11eb-9f89-bd872ec9e963.jpg)

**Comment by lc-soft** [comment]
你可以手动下载安装 vcpkg，然后给 lcpkg 配置 vcpkg 的目录路径。

https://github.com/lc-soft/lcpkg/blob/master/README.zh-cn.md#%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B

![image](https://user-images.githubusercontent.com/1730073/102374061-dd797d80-3ffb-11eb-9628-35ff1042d14e.png)

**Comment by lc-soft** [comment]
request 和 har-validator 过期只是警告，仍然可用，以后我会再花时间更新这些依赖。

**Comment by fxqy** [comment]
bootstrap-vcpkg.bat改了一下可以继续了，又需要安装vs了
![image](https://user-images.githubusercontent.com/42601163/102451102-d6418680-4072-11eb-9d05-376e0bf7bfae.png)

**Comment by fxqy** [comment]
> request 和 har-validator 过期只是警告，仍然可用，以后我会再花时间更新这些依赖。

虽然喜欢这个库，但能不能用mingw gcc来编译这个库啊，vs + vcpkg 太笨重了，我想装vs2019还不让装，不知道为啥，安装就是报错，只能安装vs2015，安装还附带了微软的全家桶sqlserver, .net, silverlight, web开发的,SSDT太多了。虽然库本身强调轻量级，但是开发环境太笨重了，普通人太难上手了，不用vs的开发者就别提了，微软的软件就是开源拦路虎。
![image](https://user-images.githubusercontent.com/42601163/102704341-1728dd80-42b5-11eb-977a-5f87ee106507.png)

**Comment by lc-soft** [comment]
这是 lcpkg 的问题， `lcpkg run` 只是简单的执行脚本，不会把 `--mode` 参数带过去，之前改脚本的时候没做测试，也没更新文档。

![image](https://user-images.githubusercontent.com/1730073/102709009-96cca180-42e1-11eb-9dc5-ebfc42050431.png)

start 脚本由这四个命令组成，你改用 npm 执行它们试试：

```bash
npm run configure -- --mode debug
npm run build:bin
npm run build:css
npm run run
```

其中 `configure` 和 `build:bin` 脚本本质上就是调用 CMake 或 XMake。

**Comment by lc-soft** [comment]
mingw gcc 我没试过，你编译时遇到哪些问题？LCUI 的 Windows 端的输入输出驱动依赖 windows API，而现有的 Makefile 是针对 Linux 写的，跑 configure 脚本时可能不会生成正确的编译和链接参数。

**Comment by zjh-nuc-AIOT** [comment]
missing script: [object Object] 咋解？

**Comment by zjh-nuc-AIOT** [comment]
运行lcpkg run start就出现missing script: [object Object] ，咋解呢？

**Comment by lc-soft** [comment]
> 运行lcpkg run start就出现missing script: [object Object] ，咋解呢？

临时解决方法：用 npm 代替 lcpkg ，我上面的评论已经解释过了。

**Comment by lc-soft** [comment]
> 运行lcpkg run start就出现missing script: [object Object] ，咋解呢？

0.3.2 版本已经修复 `missing script: [object Object]` 问题了，你再重新安装试试。

```
npm install -g lcpkg@0.3.2
```

**Comment by lc-soft** [comment]
构建配置已更新，要是还不行的话，你可以对比自己本地环境跑的脚本及输出的内容是否与 GitHub Actions 上的输出一致。

https://github.com/lc-ui/lcui-router-app/runs/1607474952?check_suite_focus=true

https://github.com/lc-ui/lcui-router-app/blob/71e79d4d03c2d63487cc615aae4bce7e62c8bf5c/.github/workflows/ccpp.yml#L5-L27

![image](https://user-images.githubusercontent.com/1730073/103119359-f940eb80-46ad-11eb-9e73-77b1aa021b85.png)

**Comment by zjh-nuc-AIOT** [comment]
[run]
ERROR: the application is not working properly.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! lcui-router-app@0.1.0 run: `node ./scripts/run.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the lcui-router-app@0.1.0 run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\宏\AppData\Roaming\npm-cache\_logs\2020-12-27T09_48_28_590Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! lcui-router-app@0.1.0 start: `npm run configure && npm run build:bin && npm run build:css && npm run run`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the lcui-router-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\宏\AppData\Roaming\npm-cache\_logs\2020-12-27T09_48_28_646Z-debug.log
感觉就差一步了，话说必须需要vs2015的支持吗，安装了vs2019就不行吗

**Comment by zjh-nuc-AIOT** [comment]
[run]
ERROR: the application is not working properly.
child_process.js:674
    throw err;
    ^

Error: Command failed: node ./scripts/run.js
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at Command.runScript (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\src\run-script.js:15:3)
    at Command.listener [as _actionHandler] (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\node_modules\commander\index.js:1002:14)
    at Command.parse (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\node_modules\commander\index.js:801:10)
    at Object.<anonymous> (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\src\cli-run-script.js:7:4)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 10216,
  stdout: null,
  stderr: null
}
child_process.js:674
    throw err;
    ^

Error: Command failed: lcpkg run configure && lcpkg run build:bin && lcpkg run build:css && lcpkg run run
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at Command.runScript (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\src\run-script.js:15:3)
    at Command.listener [as _actionHandler] (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\node_modules\commander\index.js:1002:14)
    at Command.parse (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\node_modules\commander\index.js:801:10)
    at Object.<anonymous> (C:\Users\宏\AppData\Roaming\npm\node_modules\lcpkg\src\cli-run-script.js:7:4)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 17580,
  stdout: null,
  stderr: null
}

**Comment by lc-soft** [comment]
@zhangjianhong111  进 app 目录，手动双击 app.exe 文件，看看报什么错，顺便再把 app 目录的文件列表截图发上来。

**Comment by lc-soft** [comment]
@zhangjianhong111  我看你贴日志还是在跑 start 脚本，你按照我上面的评论跑这几个命令看看有什么输出。

![image](https://user-images.githubusercontent.com/1730073/103186649-529e5a00-48fc-11eb-957f-057e4a11d912.png)

**Comment by zjh-nuc-AIOT** [comment]
![image](https://user-images.githubusercontent.com/57065248/103186995-a65d7300-48fd-11eb-9812-954e8052efd6.png)

**Comment by zjh-nuc-AIOT** [comment]
![Uploading image.png…]()

**Comment by lc-soft** [comment]
@zhangjianhong111  app 目录的文件列表截图呢？

**Comment by zjh-nuc-AIOT** [comment]
![image](https://user-images.githubusercontent.com/57065248/103187920-4ff23380-4901-11eb-8910-1cd5d9c8e4bb.png)

**Comment by zjh-nuc-AIOT** [comment]
![image](https://user-images.githubusercontent.com/57065248/103187940-64cec700-4901-11eb-9c04-454e4988f55e.png)

**Comment by lc-soft** [comment]
@zhangjianhong111 脚本输出的内容就这么点吗？把前面跑的脚本的输出都贴出来。

```
[run]
ERROR: the application is not working properly.
child_process.js:674
throw err;
```

**Comment by zjh-nuc-AIOT** [comment]
> lcui-router-app@0.1.0 configure D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> node ./scripts/configure.js "--mode" "debug"

'xmake' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[configure]
'xmake' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
write config to D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\config\builder.json:
{ mode: 'debug', arch: 'x64', tool: 'cmake' }
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/baiduyunxiazai/qs/lcui-router-app-master (1)/lcui-router-app-master/build
PS D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master> npm run build:bin

> lcui-router-app@0.1.0 build:bin D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> node ./scripts/build-bin.js


[build]
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.4.0+e901037fe

  Checking Build System
  AppLib.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\build\src\lib\Debug\AppLib.lib
  AppUI.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\build\src\ui\Debug\AppUI.lib
  about.c
  AppUIComponents.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\build\src\ui\components\Debug\AppUIComponents.lib
  AppUIViews.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\build\src\ui\views\Debug\AppUIViews.lib
  ui.c
  app.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\app\Debug\app.exe
  Building Custom Rule D:/baiduyunxiazai/qs/lcui-router-app-master (1)/lcui-router-app-master/CMakeLists.txt

[after build]
exporting LCUI:x64-windows-release
exporting lcui-router:x64-windows-release
exporting lc-design:x64-windows-release
PS D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master> npm run build:css

> lcui-router-app@0.1.0 build:css D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> node ./scripts/build-css.js

compile stylesheets...
Rendering Complete, saving .css file...
Wrote CSS to D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\app\assets\stylesheets\app.css
PS D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master> npm run run

> lcui-router-app@0.1.0 run D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> node ./scripts/run.js

run application...

[run]
ERROR: the application is not working properly.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! lcui-router-app@0.1.0 run: `node ./scripts/run.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the lcui-router-app@0.1.0 run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\宏\AppData\Roaming\npm-cache\_logs\2020-12-28T03_37_08_968Z-debug.log
PS D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master>

**Comment by zjh-nuc-AIOT** [comment]
麻烦了，最近学校在交课设，这不想用下这个

**Comment by zjh-nuc-AIOT** [comment]
PS D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master> npm start

> lcui-router-app@0.1.0 start D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> npm run configure && npm run build:bin && npm run build:css && npm run run


> lcui-router-app@0.1.0 configure D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> node ./scripts/configure.js

'xmake' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[configure]
'xmake' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
write config to D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\config\builder.json:
{ mode: 'release', arch: 'x64', tool: 'cmake' }
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/baiduyunxiazai/qs/lcui-router-app-master (1)/lcui-router-app-master/build

> lcui-router-app@0.1.0 build:bin D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> node ./scripts/build-bin.js


[build]
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.4.0+e901037fe
版权所有(C) Microsoft Corporation。保留所有权利。

  AppLib.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\build\src\lib\Debug\AppLib.lib
  AppUI.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\build\src\ui\Debug\AppUI.lib
  about.c
  AppUIComponents.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\build\src\ui\components\Debug\AppUIComponents.lib
  AppUIViews.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\build\src\ui\views\Debug\AppUIViews.lib
  ui.c
  app.vcxproj -> D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\app\Debug\app.exe

[after build]
exporting LCUI:x64-windows-release
exporting lcui-router:x64-windows-release
exporting lc-design:x64-windows-release

> lcui-router-app@0.1.0 build:css D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> node ./scripts/build-css.js

compile stylesheets...
Rendering Complete, saving .css file...
Wrote CSS to D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master\app\assets\stylesheets\app.css

> lcui-router-app@0.1.0 run D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master
> node ./scripts/run.js

run application...

[run]
ERROR: the application is not working properly.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! lcui-router-app@0.1.0 run: `node ./scripts/run.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the lcui-router-app@0.1.0 run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\宏\AppData\Roaming\npm-cache\_logs\2020-12-28T03_45_17_707Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! lcui-router-app@0.1.0 start: `npm run configure && npm run build:bin && npm run build:css && npm run run`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the lcui-router-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\宏\AppData\Roaming\npm-cache\_logs\2020-12-28T03_45_17_765Z-debug.log
PS D:\baiduyunxiazai\qs\lcui-router-app-master (1)\lcui-router-app-master>

**Comment by zjh-nuc-AIOT** [comment]
我没装vs2015，有vs2019 我这些命令是在vscode下执行的

**Comment by lc-soft** [comment]
@zhangjianhong111 我在 Windows 上跑了一次，已经知道问题了：

- app.exe 没有输出在 app 目录里
- 默认配置的是 release 模式，CMake 实际上还是以 debug 模式编译
- lc-design 的资源目录多套了一层 app 目录，app/assets 变成了 app/app/assets

**Comment by lc-soft** [comment]
> 我没装vs2015，有vs2019 我这些命令是在vscode下执行的

与 vs2015 无关，我 vs2017 都能编译通过。

**Comment by zjh-nuc-AIOT** [comment]
那要如何修改下呢？

**Comment by zjh-nuc-AIOT** [comment]
太麻烦你了

**Comment by zjh-nuc-AIOT** [comment]
大佬加油完善

**Comment by lc-soft** [comment]
@zhangjianhong111 晚上我花点时间再改改。

**Comment by zjh-nuc-AIOT** [comment]
爱你，大佬。

**Comment by lc-soft** [comment]
@zhangjianhong111  Windows 的构建脚本已更新，你再下载这个项目跑一遍脚本试试。

**Comment by zjh-nuc-AIOT** [comment]
成功了感谢

**Comment by zjh-nuc-AIOT** [comment]
![image](https://user-images.githubusercontent.com/57065248/103258984-64eac780-49d2-11eb-830b-7050dc8856c8.png)

**Comment by zjh-nuc-AIOT** [comment]
大佬牛逼
